name: ML Ops CI
on:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: iterative/setup-cml@v2
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up DVC & Pull Data
      env:
        GCP_CREDS: ${{ secrets.GCP_CREDS }}
      run: |
        echo "$GCP_CREDS" > gcp-creds.json
        pip install dvc[gs]
        export GOOGLE_APPLICATION_CREDENTIALS=gcp-creds.json
        dvc pull
    
    - name: Run Tests
      run: |
        python -m train
        pytest tests/ > result.txt

    - name: Report with CML
      env:
        REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
      run: |
        echo "## Test Report from CI" > report.md
        cat result.txt >> report.md
        cml comment create --publish report.md
